// <auto-generated />
using System;
using GridLayoutEditor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridLayoutEditor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GridLayoutEditor.Models.GridItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LayoutVersionId");

                    b.ToTable("GridItems");
                });

            modelBuilder.Entity("GridLayoutEditor.Models.LayoutVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LayoutVersions");
                });

            modelBuilder.Entity("GridLayoutEditor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GridLayoutEditor.Models.GridItem", b =>
                {
                    b.HasOne("GridLayoutEditor.Models.LayoutVersion", "LayoutVersion")
                        .WithMany("GridItems")
                        .HasForeignKey("LayoutVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutVersion");
                });

            modelBuilder.Entity("GridLayoutEditor.Models.LayoutVersion", b =>
                {
                    b.HasOne("GridLayoutEditor.Models.User", "User")
                        .WithMany("LayoutVersions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GridLayoutEditor.Models.LayoutVersion", b =>
                {
                    b.Navigation("GridItems");
                });

            modelBuilder.Entity("GridLayoutEditor.Models.User", b =>
                {
                    b.Navigation("LayoutVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
